Feature
WebThingsIO/gpio-adapter pull request #41
Opened 2020-06-10 08:54 UTC by the-real-not-a-number

added momentary action to 'on/off switch'

2020-06-10 18:44 UTC, mrstegeman requested changes
Please also restore the deleted files.

2020-06-10 18:44 UTC, mrstegeman commented on gpio-adapter.js
> +          value = 0;
You're setting `value = 0` here, which means the ternary in the next line is meaningless.

2020-06-10 18:44 UTC, mrstegeman commented on manifest.json
> +          "latching": true,
This seems to be unused.

2020-06-10 18:44 UTC, mrstegeman commented on package.json
> +                "minimum": 0
This minimum is missing from the `package.json` patch above.

2020-06-10 18:44 UTC, mrstegeman commented on package.json
> +              "unlatch": {
I know the others don't already have this, but can you add a meaningful `title` and `description` to the two new config items, both here and in `manifest.json`?

2020-06-11 10:07 UTC, the-real-not-a-number commented
requested amendments effected

2020-06-11 16:27 UTC, mrstegeman commented
There are no new commits...

2020-06-11 22:45 UTC, mrstegeman requested changes

2020-06-11 22:45 UTC, mrstegeman commented on gpio-adapter.js.js
> +              reject(err);
You're attempting to reject/resolve the same promise twice here. You can just omit the `reject(err)` here and the `resolve(this.value)` below.

2020-06-11 22:45 UTC, mrstegeman commented on package.json
> +<<<<<<< HEAD
Please resolve these merge errors.

2020-06-11 22:45 UTC, mrstegeman commented on package.json
> +    "url": "git+https://github.com/mozilla-iot/gpio-adapter.git"
This change is unnecessary.

2020-06-11 23:04 UTC, mrstegeman commented
Looks like you've now deleted `package.json` all together and changed the permissions on `package.sh`.

2020-06-12 00:20 UTC, mrstegeman requested changes
Please also revert the file permissions on `package.sh`.

2020-06-12 00:20 UTC, mrstegeman commented on gpio-adapter.js
> +              reject(err);
Remove the reject and resolve below, they’re unnecessary

2020-06-12 18:05 UTC, closed without merging